# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.236
neo_version_range=[21,)
loader_version_range=[4,)

# Mod
mod_id=firmalifehardcore
mod_name=FirmaLife HardCore
mod_license=MIT
mod_version=0.2.1-beta
mod_group_id=com.yukimods.firmalifehardcore
mod_authors=Coin0804
mod_description=复古物语式地窖/温室机制 — 材质热阻 + 封闭空间检测 + 抛弃ClimateStation的全局追踪器

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
